### ISSUE TITLE
Why are all the caches named 'vcpkg'?

### ISSUE THREAD

**Issue by LegalizeAdulthood** [lukka/CppCMakeVcpkgTemplate#13]
I'm not sure if this is coming from your github action or from vcpkg, but I get a cache per dependency, but they're all named 'vcpkg' so I can't see what they are and I can't invalidate a particular one manually should that become necessary.

**Comment by LegalizeAdulthood** [comment]
![image](https://github.com/lukka/CppCMakeVcpkgTemplate/assets/4270863/c7ccc154-3ebd-4e33-a953-0b49e2bf2c8b)

**Comment by lukka** [comment]
@LegalizeAdulthood the cache is created by vcpkg, not by the `run-vcpkg` action. Please create a new issue on the vcpkg issue section if you believe this is a problem.
