### ISSUE TITLE
Licence question

### ISSUE THREAD

**Issue by karl-brandt-andersen** [lukka/CppCMakeVcpkgTemplate#23]
Hey

I am a young programmer and i would like to use your template for my projects.
Am i allowed with the licence you use, to "take" this template, manipulate it and use it in my own projects?

**Comment by lukka** [comment]
@karl-brandt-andersen  you can use this template to create any project you'd like, no restrictions apply if you use to create your own project.

Only the case where this template is extended and offered as a template again, the copyright notice needs to be included.
