### ISSUE TITLE
Add `.vscode/extensions.json`

### ISSUE THREAD

**Issue by chinwobble** [lukka/CppCMakeVcpkgTemplate#28]
`.vscode/extensions.json` is a file used by vscode to recommend extensions to users.
This will help new users to the repo get started with vscode.

```json
{
	"recommendations": [
		"ms-vscode.cpptools",
		"ms-vscode.cmake-tools"
	],
	"unwantedRecommendations": [

	]
}
```

**Comment by lukka** [comment]
@chinwobble yes, mind creating a PR?

**Comment by lukka** [comment]
@chinwobble thank you!
