### ISSUE TITLE
Add .clang-format and .clang-tidy

### ISSUE THREAD

**Issue by chinwobble** [lukka/CppCMakeVcpkgTemplate#31]
This template is great and I used it to get started on a new c++ project easily!

Would you be open to me creating a PR with `.clang-format` and `.clang-tidy` to this repo?

I'm new to C++ and not sure what are the most popular tools but seems like linting and formatting are essential especially in c++.

**Comment by lukka** [comment]
@chinwobble sure yes, go ahead, I'd be happy to have those files as well.
