### ISSUE TITLE
How to change preset in Visual Studio [Debug, Release, RelWithDebInfo etc.]

### ISSUE THREAD

**Issue by trebla64** [lukka/CppCMakeVcpkgTemplate#7]
Hi,

Firstly, thanks for your template. I use it in all my C++ projects now.

By default visual studio builds the "Debug" preset and I haven't been able to find a way to use the other presets. It seems you can change this in VS code but my vscode builds keep failing.

I have searched everywhere for how to do this. Maybe I'm missing something stupid.

There is a way to build using cmake like in the yaml file, but this seems to always reconfigure everything and doesn't use cached packages.

Any help would be appreciated, thanks.

**Comment by lukka** [comment]
@trebla64 please take a look at https://github.com/lukka/CppCMakeVcpkgTemplate/pull/8
Does it satisfy your request?

**Comment by trebla64** [comment]
Yes. Have tested it and looks like it works.

Thanks

**Comment by lukka** [comment]
@trebla64 thanks for the suggestion, the configuration selection was definitively missing when using IDEs. Let me know if you have more suggestions, thanks!
